### ISSUE TITLE
拆分长文本失效，

### ISSUE THREAD

**Issue by QQQOrange** [leolee9086/quickRefactor#3]
具体材料以下如下，只保留重构助手尝试
以下是具体材料和思源报错
![image](https://github.com/leolee9086/quickRefactor/assets/62794181/b3ee885d-ad17-452e-94c6-005d91c2d0f5)
[哲学导论 (张世英) (Z-Library).zip](https://github.com/leolee9086/quickRefactor/files/14217356/Z-Library.zip)
这是测试的书籍，请通过导入工具导入后测试

**Comment by leolee9086** [comment]
新版应该已经修复了这个问题，issue我先关闭了

**Comment by QQQOrange** [comment]
> 新版应该已经修复了这个问题，issue我先关闭了

谢谢老哥
